# REI505M Machine Learning - Final project
### Due: --------

**Names**: Axel Kristján Axelsson, Bjarni Haukur Bjarnason <br />
**Email**: aka30@hi.is, bhb23@hi.is

**1. Image classification**

s


In [1]:
from data_loader import MyDataLoader
%load_ext autoreload 
%autoreload 2
dl = MyDataLoader("combine2", (128,128))



In [2]:
dl.normalize_train_data(norm_size=(128,128))

100%|██████████| 102/102 [00:54<00:00,  1.89it/s]


In [2]:
try:
    del X
    del y

except:
    pass

X, y = dl.get_lab_data()

100%|██████████| 102/102 [00:57<00:00,  1.77it/s]


In [3]:
import numpy as np

print(X.shape)
print(y.shape)
print(np.max(X))
print(np.min(X))
print(np.max(y))
print(np.min(y))

(11636, 128, 128, 1)
(11636, 128, 128, 2)
100
0
97
-107


In [4]:
X_lab = X/100
y_lab = y/128

In [5]:
import numpy as np

print(np.max(X_lab))
print(np.max(y_lab))
print(np.min(X_lab))
print(np.min(y_lab))

1.0
0.7578125
0.0
-0.8359375


In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_lab, y_lab, test_size = 0.3, random_state = 3)
X_test, X_val, y_test, y_val = train_test_split(X_test, y_test, test_size = 0.33, random_state = 3)

In [17]:
# import tensorflow as tf
# tf.keras.backend.clear_session()

In [8]:

from keras.layers import Input, Conv2D, BatchNormalization, UpSampling2D, Dense, InputLayer
from keras.models import Model
from keras.regularizers import l2
from tensorflow.keras.optimizers import Adam
from keras import Sequential


img_shape = (128, 128, 1)
kernel_size = (3,3)
num_filters = 64

try:
    del model
except:
    pass

model = Sequential()
model.add(InputLayer(input_shape=img_shape))
model.add(Conv2D(num_filters, kernel_size, activation='relu', padding='same'))
model.add(Conv2D(num_filters, kernel_size, activation='relu', padding='same', strides=2))
model.add(Conv2D(num_filters*2, kernel_size, activation='relu', padding='same'))
model.add(Conv2D(num_filters*2, kernel_size, activation='relu', padding='same', strides=2))
model.add(Conv2D(num_filters*4, kernel_size, activation='relu', padding='same'))
model.add(Conv2D(num_filters*4, kernel_size, activation='relu', padding='same', strides=2))
model.add(Conv2D(num_filters*8, kernel_size, activation='relu', padding='same'))
model.add(Conv2D(num_filters*4, kernel_size, activation='relu', padding='same'))
model.add(Conv2D(num_filters*2, kernel_size, activation='relu', padding='same'))
model.add(UpSampling2D((2, 2)))
model.add(Conv2D(num_filters, kernel_size, activation='relu', padding='same'))
model.add(UpSampling2D((2, 2)))
model.add(Conv2D(32, kernel_size, activation='relu', padding='same'))
model.add(Conv2D(2, kernel_size, activation='sigmoid', padding='same'))
model.add(UpSampling2D((2, 2)))

model.compile(optimizer='rmsprop', loss='msle')

In [9]:
model.fit(X_train[:1000], y_train[:1000], batch_size = 32, epochs = 10)


Epoch 1/10
32/32 [==============================] - 9s 77ms/step - loss: 0.0263
Epoch 2/10
32/32 [==============================] - 2s 65ms/step - loss: 0.0229
Epoch 3/10
32/32 [==============================] - 2s 50ms/step - loss: 0.0229
Epoch 4/10
32/32 [==============================] - 2s 49ms/step - loss: 0.0229
Epoch 5/10
32/32 [==============================] - 2s 49ms/step - loss: 0.0229
Epoch 6/10
32/32 [==============================] - 2s 49ms/step - loss: 0.0229
Epoch 7/10
32/32 [==============================] - 2s 49ms/step - loss: 0.0229
Epoch 8/10
32/32 [==============================] - 2s 49ms/step - loss: 0.0229
Epoch 9/10
32/32 [==============================] - 2s 50ms/step - loss: 0.0229
Epoch 10/10
32/32 [==============================] - 2s 49ms/step - loss: 0.0229


In [12]:
from nn_helper import save_model, load_model, delete_model

save_model(model, "model_a")

Directory already exists, overwrite?
INFO:tensorflow:Assets written to: model_a\assets


In [13]:
model = load_model("model_a")

In [21]:
# model.fit(X_train, y_train, batch_size = 32, epochs = 100, validation_data=(X_val, y_val))
pred = model.predict(np.expand_dims(np.divide(X_test[:100],100),-1))
pred = pred*128



NameError: name 'model' is not defined

In [19]:

mynd = pred[1]
fokking = np.zeros((128,128,3))
print(X_test[1].shape)
fokking[:,:,0] = X_test[1]
fokking[:,:,1:] = mynd
fokking = fokking.astype(int)
print(np.max(fokking))
print(np.min(fokking))

NameError: name 'pred' is not defined

In [15]:
drasl = color.lab2rgb(fokking)
print(np.max(drasl))
print(np.min(drasl))

4.501204800696596e-10
0.0


In [16]:
from PIL import Image

img = Image.fromarray(drasl)

imgO = Image.fromarray(X_test[1])
# imgTrue = Image.fromarray(y_test[1], 'RGB')
# img = Image.fromarray(mynd1, 'RGB')
imgO.show()
# imgTrue.show()
img.show()

TypeError: Cannot handle this data type: (1, 1, 3), <f8

In [18]:
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))


Num GPUs Available:  1


In [22]:
print(X.shape)
print(X[11001])


(11636, 500, 500)
[[184 184 184 ... 187 187 187]
 [184 184 184 ... 187 187 187]
 [184 184 184 ... 187 187 187]
 ...
 [169 167 166 ... 209 209 209]
 [171 169 167 ... 209 209 209]
 [172 170 168 ... 209 209 209]]


In [7]:


# print(X.shape)
# print(X_test.shape)
# im = Image.fromarray(X_train[0], mode="YCbCr")
# im.show()
# print(X_test[0])

(9262, 500, 500, 3)
(9262, 500, 500, 3)
[[[ 55  45  35]
  [ 56  46  36]
  [ 56  46  36]
  ...
  [ 47  43  31]
  [ 47  43  31]
  [ 47  43  31]]

 [[ 52  42  32]
  [ 53  43  33]
  [ 54  44  34]
  ...
  [ 52  48  36]
  [ 52  48  36]
  [ 52  48  36]]

 [[ 49  39  29]
  [ 50  40  30]
  [ 51  41  31]
  ...
  [ 55  51  39]
  [ 55  51  39]
  [ 55  51  39]]

 ...

 [[146 106 107]
  [146 106 107]
  [145 105 105]
  ...
  [165 158 166]
  [165 158 166]
  [165 158 166]]

 [[158 118 119]
  [158 118 119]
  [157 117 117]
  ...
  [175 168 176]
  [175 168 176]
  [175 168 176]]

 [[165 125 126]
  [164 124 125]
  [164 124 124]
  ...
  [180 173 181]
  [180 173 181]
  [180 173 181]]]


In [8]:
from PIL import Image
import numpy as np

img = Image.open("test.jpg").convert('L')
img = img.resize((500,500))
img.show()
arr = np.array(img)

In [18]:
from PIL import Image
import numpy as np

img = Image.open("bla.jpg")
img = img.resize((500,500))
x=np.ndarray((500,500,3), dtype=np.short)
img0 = Image.fromarray(x)

TypeError: Cannot handle this data type: (1, 1, 3), <i2